# Generated by Django 5.2.4 on 2025-07-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('in_use', 'In Use'), ('damaged', 'Damaged'), ('disposed', 'Disposed')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
