# Generated by Django 5.2.4 on 2025-07-05 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='assets_asse_categor_6e0f49_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name', 'serial_number'], name='assets_asse_name_73375e_idx'),
        ),
    ]
